### ISSUE TITLE
app crashed on Sony XL39h

### ISSUE THREAD

**Issue by lmk123** [tjwoon/csZBar#9] opened 2015-02-03 08:13 UTC
Hi , I use your plugin in my PhoneGap project , it works well , except on [Sony XL39h](http://www.sonymobile.com/us/products/phones/xperia-z-ultra/) !

Follow is my code:
```js
cloudSky.zBar.scan( {} , alert , alert );
```

When I call `.scan()` method , mobile will open camera , but then it alert me "Sorry , App has been crashed" , and I click `OK` , then the app auto restart.

I hope you can fix it :)

**Comment by PaoloMessina** [comment] 2015-02-13 07:53
@lmk123 
I have the same problem, try to get the logcat and find if the problem is on the autofocus.
We solve the autofocus change in my pull request and on another sony the app stop to crash!

https://github.com/tjwoon/csZBar/pull/11

**Comment by dasgib** [comment] 2015-02-23 09:49
I can confirm this issue. Tried on Moto E (4.4.4), Xcover 2 (4.1.2), Nexus 7 (5.0.2), HTC M7 (4.4.3), Moto G (4.4.4) - crashes everywhere, without auto-restart. Hope your pull-request will be merge soon :)

**Comment by tjwoon** [comment] 2015-02-27 11:06
This should be fixed now, thanks to @PaoloMessina's pull request #11

**Closed** 2015-02-27 11:06 UTC
Labels: bug
