### ISSUE TITLE
Release latest

### ISSUE THREAD

**Issue by dcousens** [tjwoon/csZBar#70] opened 2016-05-11 10:57 UTC
**edit**: We really need to get the update out ASAP,  as iOS crashes otherwise

**Comment by jjbridges** [comment] 2016-05-17 19:38
Looking forward to these updates.

**Comment by tjwoon** [comment] 2016-05-19 16:09
Shall we make v1.3.4 contain those fixes which can be done/merged relatively quickly, and leave the stuff which require more time to v1.4.0?

In fact depending on the list of changes to be done, I think it may be better for the upcoming to be v1.4.0 followed by v1.5.0.

**Comment by tjwoon** [comment] 2016-05-19 16:14
I propose to include these in the upcoming release:

- #64 
- #57 
- #50 
- #49

**Comment by dcousens** [comment] 2016-05-20 01:11
@tjwoon indeed,  most of the above should be fixed,  I just haven't had time to take it to a number of devices and thoroughly test yet.

**Comment by pgbpaulo** [comment] 2016-05-20 12:18
Hi!
Do you have any date in mind for the next release?

**Comment by uniphonic** [comment] 2016-05-20 14:02
@tjwoon Sounds good to me, except I think maybe we should leave out #49. I think all of those have code fixes that have already been committed, with the exception of #49, which I was not able to reproduce. Everything else is already in master, correct? I think we should go ahead and release what we've got in master right now.

I just tested it out the latest from master on a Samsung Galaxy S4, Nexus 5x, iPhone 6, and iPhone 4s, and it seems to be working fine for me. I had done more extensive testing on PR #65 , and didn't see any problems there either.

**Comment by jjbridges** [comment] 2016-05-20 14:18
I also have the issue #49, I cannot get the flash to come on.  Testing with a Samsung S5.  I had my fingers crossed to get that fix in the next release.  I have other people stating the same that it doesn't work.  This conversation probably should trail into #49 discussion.

**Comment by tjwoon** [comment] 2016-05-23 15:20
Wow, progress spends awesome!

I'll test #49 on some of my devices

**Comment by halmechanic** [comment] 2016-08-17 21:29
When could we expect a release with these fixes? Especially fixes #78 and #50 are quite important.

**Comment by dcousens** [comment] 2016-08-17 22:39
For me,  I have to release this and do a production testing set within the next month.

**Comment by dcousens** [comment] 2016-11-11 06:53
Related https://github.com/tjwoon/csZBar/issues/92

**Comment by dcousens** [comment] 2016-11-11 06:54
Related https://github.com/tjwoon/csZBar/issues/87

**Closed** 2018-02-01 06:35 UTC
Labels: help wanted, question
