### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by dtmp** [tjwoon/csZBar#84] opened 2016-09-19 10:05 UTC
I faced problem while processing binary file of my app in iTunes Connect after uploading. I spend few days trying to resolve it. My app built, signed and uploaded to iTunes Connect successfuly. Then file appeared in the binary file list on iTunes Connect, but after 1-2 minutes binary file disappeared from list whithout any error message.

The error was at cordova-plugin-cszbar. This is the command to install plugin from your manual:

cordova plugin add cordova-plugin-cszbar

Running this command you will install old version of this plugin. It was very difficult to find what actually cause problem because I installed plugin using command from your manual.

The problem was solved by installing this plugin from git repository by this command:

cordova plugin add https://github.com/tjwoon/csZBar

Please, update installation command in manual or update to the last stable version repository where current installation command downloaded plugin.

I use this enviroment:

Xcode 8.0 (8A218a)
Cordova 6.3.1
Npm 3.10.3
Node 6.6.0

Thank you for your plugin =-)

**Comment by dcousens** [comment] 2016-09-19 14:17
Duplicate of
https://github.com/tjwoon/csZBar/issues/81
https://github.com/tjwoon/csZBar/issues/82
https://github.com/tjwoon/csZBar/issues/85

See #70

**Closed by dcousens** 2016-09-19 14:17 UTC
